### ISSUE TITLE
Lead-ins : all created lead-ins will be displayed on the homepage

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/International-Maritime-Services#3]
![image](https://cloud.githubusercontent.com/assets/12791909/10302724/2c99131a-6c41-11e5-8e4c-67e6d610002d.png)

**Comment by Rahul-titan** [comment]
As per the design, there is no limit for lead-ins display on homepage.
Should i show only 4 lead-ins on home page?

**Comment by ermatitan** [comment]
Hello Rahul, 

Please display only 4 lead-ins in the homepage, as per conversation with my manager. Thanks
