### ISSUE TITLE
Newly created boats not displayed on the homepage. How many custom boat post can the homepage displayed? 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/International-Maritime-Services#6]
![image](https://cloud.githubusercontent.com/assets/12791909/10303314/7012cec0-6c45-11e5-8dee-470f28447c66.png)

**Comment by Rahul-titan** [comment]
Only 4 boats-custom posts will display on Home page, Remaining all post are displaying on 
Ship Delivery Track record Page, if there is any change please inform me.
